travis:
  secure:
    BINSTAR_TOKEN: 4fm9fa1xmGkUVcHuf/rBfE/agIrOdxKorj0j5rM66EAC6CoURcrYxi7Cni5vlhBQLBCQsfUUXcaAeXjRMxd4LNiq5jr2OdvTZDAK069QYmFcwGZ+Wc8Y7gGNdBh+YvShVoCVXcss6BrTTY5PNZ/PpRri48Hoenwcd+S/VXs6E2WHundo0x+w4bYAlyZCGMNjAZfY8wqEPJiOrEETV/ZVLeCfOJ3zIN+89SjQtNh5vbwbyIyLQ0x0NjZHB2SwmKAIBqbjqYpYE7XLkMVZCwxKnUOBFqFJDjkLQsPc5JqfTBtlaX4xqxyTA0gZc6+3GD7o+3BiC9M/zWUa0qTP1SmPueSRaCUwGIwZ+HMLs7oYbREbD+wS60ULlKmK1UPONZWaHdbeebjvi70l6P5dnilzrMZKIkPVefgYe5x8CUBQtFrKAQPQiz/fJ5jTIE1ll7gZC8H/VgVKRW5OIwyUAVTR06VcPc+4FluQpCR+pSjZ/NFTEX4pwH+O6S3TRoKc/g1IBTgwlJeQq30LxELcG0aE7iAiTMP8YcdCcx4xt0Wbi54d6TgkW8Xy+qxNmX/8vmzbrTUC+aVjjJPqZ4+3mquLuZI2dOr+lftq4PFFcRsBjtKPOL4Hqp/VMpIvqGh5t2SXMtNK4LbtqN3cmxZwNGPUcBCEz/c7l41nRq2o8Axo4K8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
